### ISSUE TITLE
Allow to set the initial store

### ISSUE THREAD

**Issue by yordis** [anish000kumar/redux-box#13]
I don't see a way I could setup the initial state of the store right now.

**Comment by anish000kumar** [comment]
The state file of each module represents the initial state.

**Comment by yordis** [comment]
@anish000kumar I am talking about the whole store, like, when you could pass down `window.__SERVER_SIDE_STORE_STATE` and you rehydrate the store using those values.

**Comment by anish000kumar** [comment]
@yordis  I guess, you should be able to do this with redux-box. Can you share some relevant snippet showing what you could do with redux, that's not fitting with redux-box?

**Comment by yordis** [comment]
@anish000kumar that is part of the `store` creation

**Comment by MyNameReallySux** [comment]
I have to agree with @yordis, there is no clear way to set the initial store from the server or cache, without spitting and handling logic for each module manually. The problem is that redux's `createStore` method can take 3 arguments, one being `preloadedState`, and redux box has no equivalent.

[See docs.](https://github.com/reactjs/redux/blob/master/docs/api/createStore.md)

This is useful if you have, as was stated, server side rendering of state or cache-persisted state. This can be solved externally by simply looping over each module and setting the state before executing the redux-box `createStore`. But setting state this way would require that 100% of the redux logic use redux box, and would mean you could not incrementally add redux box to a large project.

Would look something like this...

```javascript
import testModule from './test'

let persistedStore = loadPersistedStore()

let modules = [testModule]
modules = modules.map(module => {
    if(persistedStore && persistedStore[module.name]){
        module.state = persistedStore[module.name]
    }
   return module
})

createStore(modules, ... )
```
My suggestion is something like this....

```javascript
let persistedStore = loadPersistedStore()

createStore([...arrayOfModules], { /* config */
    persistedStore: { /* persisted store would go here */ }
})
```

`createStore` would be modified to handle the `persistedStore` config property. Then, `storeCreator` (aka redux's createStore) should accept 'persistedStore' as the second parameter if it exists. This will cover state both handled and not handled by redux box (which is pretty important if you want to start using redux box in a large code base)

```javascript
let enhancers = composeEnhancers( applyMiddleware(...middlewares)
let store = persistedState 
    ? storeCreator(combinedReducer, persistedState, enhancers)
    : storeCreator(combinedReducer, enhancers)
```

I personally think this issue should be reopened, or at least discussed in a better way. Please let me know your concerns and if you would want this to be a feature.

**Comment by anish000kumar** [comment]
You should be able to do this in latest versions of redux-box. I have also updated the docs to reflect this point. It would pretty much the same way as suggested by you, except the property is named `preloadedState`,  to keep the terminologies differences minimal between redux and redux-box.

example:

```javascript
import {createStore} from 'redux-box'
import {module as userModule} from './user'

const config ={ 
  preloadedState: {
    name: 'test',
    email: 'test@tests.com'
  }
}

export default createStore([], config)
```

https://stackblitz.com/edit/react-qcasn4?file=store%2Findex.js

**Comment by MyNameReallySux** [comment]
Awesome, thanks for the update. Will test the new code soon.
