### ISSUE TITLE
How to integrate react routerv4 web version?

### ISSUE THREAD

**Issue by AyumiKai** [anish000kumar/redux-box#23]
How to integrate react routerv4 web version?

**Comment by anish000kumar** [comment]
React router and redux are usually not coupled together (which is the recommended practise as well), so it should work well  out of the box. There are few noteworthy points however (related to redux actually, rather than redux-box), as stated here: 
https://reacttraining.com/react-router/web/guides/redux-integration
In case you meant integrating https://github.com/supasate/connected-react-router, then it exports a middleware  which you can simply register in the `middlewares` array, at the time of store creation.
